################################################################################
# Visuals
################################################################################

# Support true color in terminal
set -g default-terminal "tmux-256color"
# TODO: Ensure ghostty's GPU-accelerated colors pass through to tmux. Confim this works/is necessary.
set -ga terminal-overrides ",xterm-256color:Tc"

################################################################################
# Clipboard/copy-paste handling
################################################################################
#
# NOTE: System clipboard intergration depends on a chain of configuration. For remote systems using ghostty -> ssh (ie. et/mosh) -> tmux -> emacs:
# - ghostty must allow OSC 52 handling
# - ssh must allow OSC 52 passthrough (does by default)
# - tmux must allow OSC 52 passthrough
# - emacs must support OSC 52 handling
#
# allow-passthrough requires tmux >=3.3
set -g allow-passthrough on
set-option -s set-clipboard on