#!/usr/bin/env bash
set -e

upstream_url=$1

echo "Fork sync..."

if ! git remote -v | grep upstream >/dev/null; then
   git remote add $(upstream_url)
fi

# Sync branches
echo "Syncing branches..."
git fetch upstream
git checkout main
git merge upstream/main
git push origin main

# Sync tags
echo "Syncing tags..."
git fetch upstream --tags
git push origin --tags

echo "Fork sync... done"
