;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        capitalize-dwim
        upcase-region
        downcase-region
        upcase-word
        downcase-word
        ))

(setq mc/cmds-to-run-once
      '(
        undo-tree-visualize
        ))
